package reporter

import (
	"fmt"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/petersimmons1972/engram/internal/manifest"
	"github.com/petersimmons1972/engram/internal/types"
	"github.com/petersimmons1972/engram/internal/vram"
)

// RunInfo carries runtime context stamped into the generated documents.
type RunInfo struct {
	OllamaVersion string
	OS            string
	GPU           vram.Info
	BinaryVersion string
	Timestamp     time.Time
}

// RenderMarkdown produces the full docs/models.md content from scored results
// and the loaded manifest. The manifest supplies the excluded-model table.
func RenderMarkdown(results []types.ModelResult, m *manifest.Manifest, info RunInfo) string {
	if info.Timestamp.IsZero() {
		info.Timestamp = time.Now().UTC()
	}
	var b strings.Builder

	fmt.Fprintf(&b, "<!-- Generated by instinct-benchmark. Do not edit by hand.\n")
	fmt.Fprintf(&b, "     Re-run: go run ./cmd/benchmark\n")
	fmt.Fprintf(&b, "     Last run: %s | Ollama %s | %s | GPU: %s -->\n\n",
		info.Timestamp.Format(time.RFC3339), info.OllamaVersion, info.OS, info.GPU.Label)

	b.WriteString("# Model Compatibility\n\n")
	b.WriteString("Instinct uses a local Ollama model to detect patterns in your Claude Code sessions.\n")
	b.WriteString("This page documents which models work, which don't, and why —\n")
	b.WriteString("so you can pick the right one for your hardware without guessing.\n\n")

	best := bestRecommended(results)
	if best != nil {
		fmt.Fprintf(&b, "> **Suggested default:** `%s` (composite score %.2f, tier %s)\n\n", best.Model, best.Score.Composite, best.Tier)
	}

	b.WriteString("## Choose by VRAM\n\n")
	b.WriteString("| VRAM available | Recommended model | Notes |\n")
	b.WriteString("|----------------|-------------------|-------|\n")
	for _, tier := range []string{"≤2GB", "4-6GB", "7-10GB", "11-16GB"} {
		rec := firstRecommendedInTier(results, tier)
		if rec != nil {
			fmt.Fprintf(&b, "| %s | `%s` | %.1f GB VRAM, avg %s |\n",
				tier, rec.Model, rec.VRAMGB, rec.Score.AvgLatency.Std().Round(time.Second))
		} else {
			fmt.Fprintf(&b, "| %s | — | No tested model available |\n", tier)
		}
	}
	b.WriteString("\n")

	writeSection(&b, "## Recommended\n\n", results, types.VerdictRecommended)
	writeSection(&b, "## Usable (may need prompt tuning)\n\n", results, types.VerdictUsable)
	writeSection(&b, "## Not recommended\n\n", results, types.VerdictNotRecommended)
	writeSection(&b, "## Failed\n\n", results, types.VerdictFailed, types.VerdictTimedOut, types.VerdictPullFailed)

	excluded := m.Excluded()
	if len(excluded) > 0 {
		b.WriteString("## Rejected before testing\n\n")
		b.WriteString("| Model | Vendor | VRAM est. | Reason |\n")
		b.WriteString("|-------|--------|-----------|--------|\n")
		for _, model := range excluded {
			reason := strings.ReplaceAll(strings.TrimSpace(model.Rationale), "\n", " ")
			fmt.Fprintf(&b, "| `%s` | %s | %.1f GB | %s |\n",
				model.Name, model.Vendor, model.VRAMGB, reason)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Methodology\n\n")
	b.WriteString("- **Sample:** 40 tool-call events (deterministic fixture; use `--use-live-buffer` for live data)\n")
	b.WriteString("- **Runs:** 3 per model, median pattern count, mean latency\n")
	b.WriteString("- **Scored on:** JSON validity, pattern schema conformance, pattern count, latency\n")
	b.WriteString("- **VRAM:** estimated at Q4_K_M quantisation; actual usage varies by system\n")
	fmt.Fprintf(&b, "- **Hardware:** %s\n", info.GPU.Label)
	fmt.Fprintf(&b, "- **Last run:** %s\n\n", info.Timestamp.Format("2006-01-02 15:04 UTC"))

	b.WriteString("## Contributing\n\n")
	b.WriteString("Submit a PR editing `models/candidates.yaml`. See `CONTRIBUTING.md`.\n")
	b.WriteString("CI validates the manifest schema and — for new `include: true` models — runs the benchmark\n")
	b.WriteString("and posts results as a PR comment before merge.\n")

	return b.String()
}

func writeSection(b *strings.Builder, header string, results []types.ModelResult, verdicts ...types.Verdict) {
	var rows []types.ModelResult
	for _, r := range results {
		if slices.Contains(verdicts, r.Score.Verdict) {
			rows = append(rows, r)
		}
	}
	if len(rows) == 0 {
		return
	}
	b.WriteString(header)
	b.WriteString("| Model | Vendor | VRAM | Params | Avg latency | Patterns | Notes |\n")
	b.WriteString("|-------|--------|------|--------|-------------|----------|-------|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %.1f GB | — | %s | %d | %s |\n",
			r.Model, r.Vendor, r.VRAMGB,
			r.Score.AvgLatency.Std().Round(time.Second),
			r.Score.ValidPatterns,
			r.Score.VerdictReason)
	}
	b.WriteString("\n")
}

// bestRecommended returns the recommended model with the lowest VRAM footprint,
// breaking ties by composite score (descending). Provides the suggested default
// for users who have not yet chosen a model.
func bestRecommended(results []types.ModelResult) *types.ModelResult {
	var candidates []types.ModelResult
	for _, r := range results {
		if r.Score.Verdict == types.VerdictRecommended {
			candidates = append(candidates, r)
		}
	}
	if len(candidates) == 0 {
		return nil
	}
	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].VRAMGB != candidates[j].VRAMGB {
			return candidates[i].VRAMGB < candidates[j].VRAMGB
		}
		return candidates[i].Score.Composite > candidates[j].Score.Composite
	})
	return &candidates[0]
}

func firstRecommendedInTier(results []types.ModelResult, tier string) *types.ModelResult {
	for i := range results {
		if results[i].Tier == tier && results[i].Score.Verdict == types.VerdictRecommended {
			return &results[i]
		}
	}
	return nil
}
