package reporter_test

import (
	"strings"
	"testing"
	"time"

	"github.com/petersimmons1972/engram/internal/manifest"
	"github.com/petersimmons1972/engram/internal/reporter"
	"github.com/petersimmons1972/engram/internal/benchmark"
	"github.com/petersimmons1972/engram/internal/vram"
)

func sampleResults() []benchmark.ModelResult {
	return []benchmark.ModelResult{
		{
			Model:  "mistral:7b",
			VRAMGB: 4.5,
			Tier:   "4-6GB",
			Vendor: "Mistral AI",
			Score: benchmark.Score{
				Verdict:       benchmark.VerdictRecommended,
				ValidPatterns: 4,
				AvgLatency:    benchmark.Duration(13 * time.Second),
				Composite:     7.44,
				VerdictReason: "detected 4 valid patterns",
			},
		},
	}
}

func sampleManifest() *manifest.Manifest {
	note := "thinking leak"
	return &manifest.Manifest{
		Models: []manifest.Model{
			{Name: "mistral:7b", VRAMGB: 4.5, Tier: "4-6GB", Vendor: "Mistral AI", Family: "mistral", Instruct: true, Include: true, Rationale: "Fast and accurate."},
			{Name: "qwen3:8b", VRAMGB: 5.0, Tier: "excluded", Vendor: "Alibaba", Family: "qwen3", Instruct: true, Include: false, Rationale: "Thinking leak.", Notes: &note},
		},
	}
}

func TestRenderMarkdown_ContainsRecommended(t *testing.T) {
	info := reporter.RunInfo{OllamaVersion: "0.3.14", OS: "linux", GPU: vram.Info{GB: 20, Source: "nvidia", Label: "RTX 3090"}}
	md := reporter.RenderMarkdown(sampleResults(), sampleManifest(), info)
	if !strings.Contains(md, "mistral:7b") {
		t.Error("markdown should contain mistral:7b")
	}
	if !strings.Contains(md, "## Recommended") {
		t.Error("markdown should have Recommended section")
	}
	if !strings.Contains(md, "## Rejected before testing") {
		t.Error("markdown should have Rejected section")
	}
	if !strings.Contains(md, "qwen3:8b") {
		t.Error("markdown should list excluded model qwen3:8b")
	}
	if !strings.Contains(md, "Generated by instinct-benchmark") {
		t.Error("markdown should have generation header")
	}
}
