apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: enterprise-clearwatch-https
  namespace: clearwatch
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`enterprise.clearwatchresearch.com`)
      services:
        - name: clearwatch-enterprise-svc
          port: 80
  tls:
    secretName: clearwatchresearch-tls
