[k8s_workers]
worker131.petersimmons.com
worker132.petersimmons.com
worker133.petersimmons.com
worker134.petersimmons.com
worker135.petersimmons.com
worker136.petersimmons.com
worker137.petersimmons.com
worker138.petersimmons.com
worker139.petersimmons.com

[k8s_workers:vars]
ansible_user=psimmons
