apiVersion: ai.petersimmons.com/v1
kind: GPUHost
metadata:
  name: leviathan
  namespace: ai-fleet
spec:
  host: leviathan.petersimmons.com
  hostIP: "192.168.0.98"
  reservedMemoryGB: 8
  nfsMount: "truenas.petersimmons.com:/mnt/zp1/ai-models"
  models: []
