-- Migration 026: HyDE (Hypothetical Document Embeddings) side table.
--
-- At write-time, a hypothetical question that the memory would answer is
-- generated by a local LLM and embedded. At query-time the real question
-- is matched against these HyDE embeddings rather than raw chunk text,
-- bridging vocabulary-mismatch gaps (LME experiment #8).
--
-- Design notes:
--   - Side table (not a column on memories) to keep the memories scan clean,
--     enable a dedicated HNSW index with different ef_construction tuning,
--     and provide a clean FK path for the atoms layer (PR #986).
--   - Flag-gated (ENGRAM_HYDE_ENABLED=false default); this table is only
--     populated when the flag is ON.
--   - vector(1024) matches BAAI/bge-m3 output dimensions. Adjust if a
--     different embedder is in use — see embedder_dimensions in project_meta.
--   - ON CONFLICT DO UPDATE allows idempotent re-embedding when content
--     changes or the flag is toggled.

CREATE TABLE IF NOT EXISTS hyde_embeddings (
    memory_id   TEXT                     NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    project     TEXT                     NOT NULL DEFAULT '',
    embedding   vector(1024),
    question    TEXT,
    created_at  TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    PRIMARY KEY (memory_id)
);

CREATE INDEX IF NOT EXISTS idx_hyde_project ON hyde_embeddings(project);

-- HNSW index for ANN search. ef_construction=64 is intentionally lower than
-- the chunks HNSW (128) because hyde_embeddings is one row per memory.
CREATE INDEX IF NOT EXISTS idx_hyde_embedding_hnsw
    ON hyde_embeddings USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64)
    WHERE embedding IS NOT NULL;
