package search_test

import (
	"strings"
	"testing"

	"github.com/petersimmons1972/engram/internal/search"
	"github.com/petersimmons1972/engram/internal/types"
	"github.com/stretchr/testify/require"
)

func TestToHandles_HappyPath(t *testing.T) {
	sum := "A useful memory about foo"
	results := []types.SearchResult{
		{
			Memory: &types.Memory{
				ID:          "abc-1",
				Project:     "proj",
				Summary:     &sum,
				StorageMode: "focused",
				Content:     "full content here",
			},
			Score: 0.85,
		},
	}
	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	h := handles[0]
	require.Equal(t, "abc-1", h.ID)
	require.Equal(t, "proj", h.Project)
	require.Equal(t, sum, h.Summary)
	require.InDelta(t, 0.85, h.Score, 0.001)
	require.Equal(t, "focused", h.StorageMode)
	require.Equal(t, len("full content here"), h.Bytes)
	require.True(t, h.IsHandle)
	require.NotEmpty(t, h.FetchHint)
}

func TestToHandles_EmptyInput(t *testing.T) {
	require.Empty(t, search.ToHandles(nil))
	require.Empty(t, search.ToHandles([]types.SearchResult{}))
}

// TestToHandles_NilSummaryFallsBackToTruncatedContent covers #1260: memories
// whose Summary has not yet been generated by the async background
// summarizer (internal/summarize/worker.go, ~30s poll interval) must still
// surface something usable for handle-mode triage, instead of an empty
// string that forces a fetch-by-id for every candidate.
func TestToHandles_NilSummaryFallsBackToTruncatedContent(t *testing.T) {
	results := []types.SearchResult{
		{Memory: &types.Memory{ID: "x", Project: "p", Content: "short content, no summary yet"}, Score: 0.5},
	}
	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Equal(t, "short content, no summary yet", handles[0].Summary)
}

// TestToHandles_NilSummaryEmptyContentStaysEmpty is the zero/empty-input
// boundary: a memory with neither a summary nor content must not panic and
// must yield an empty Summary (there is nothing to fall back to).
func TestToHandles_NilSummaryEmptyContentStaysEmpty(t *testing.T) {
	results := []types.SearchResult{
		{Memory: &types.Memory{ID: "x", Project: "p", Content: ""}, Score: 0.5},
	}
	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Equal(t, "", handles[0].Summary)
}

// TestToHandles_NilSummaryLongContentTruncatedWithEllipsis is the boundary
// condition: content over 500 bytes is truncated with a trailing ellipsis,
// matching the existing detail="summary" fallback convention used elsewhere
// in this package (see the "summary" case in RecallWithOpts).
func TestToHandles_NilSummaryLongContentTruncatedWithEllipsis(t *testing.T) {
	long := strings.Repeat("a", 600)
	results := []types.SearchResult{
		{Memory: &types.Memory{ID: "x", Project: "p", Content: long}, Score: 0.5},
	}
	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Equal(t, strings.Repeat("a", 500)+"…", handles[0].Summary)
	require.Len(t, handles[0].Summary, 503) // 500 bytes + 3-byte "…" (UTF-8)
}

func TestToHandles_NilMemorySkipped(t *testing.T) {
	results := []types.SearchResult{
		{Memory: nil, Score: 0.9},
		{Memory: &types.Memory{ID: "y", Project: "p"}, Score: 0.3},
	}
	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Equal(t, "y", handles[0].ID)
}

func TestToHandles_TagsPropagated(t *testing.T) {
	results := []types.SearchResult{
		{
			Memory: &types.Memory{
				ID:      "abc-1",
				Project: "proj",
				Tags:    []string{"session:s42", "foo:bar"},
			},
			Score: 0.85,
		},
	}

	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Equal(t, []string{"session:s42", "foo:bar"}, handles[0].Tags)
}

func TestToHandles_NilTagsOmitted(t *testing.T) {
	results := []types.SearchResult{
		{
			Memory: &types.Memory{
				ID:      "abc-1",
				Project: "proj",
				Tags:    nil,
			},
			Score: 0.85,
		},
	}

	handles := search.ToHandles(results)
	require.Len(t, handles, 1)
	require.Empty(t, handles[0].Tags)
}
